In [ ]:
import pandas as pd

In [ ]:
a=pd.Series([10,20,30,40,50,60,])
a

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [ ]:
a.values

array([10, 20, 30, 40, 50, 60])

In [ ]:
a.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
a.name

In [ ]:
a.name="calaries"

In [ ]:
a

0    10
1    20
2    30
3    40
4    50
5    60
Name: calaries, dtype: int64

In [ ]:
a[0]

np.int64(10)

In [ ]:
a.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
a[0:2]

0    10
1    20
Name: calaries, dtype: int64

In [ ]:
a[2:4]

2    30
3    40
Name: calaries, dtype: int64

In [ ]:
#iloc -> location based index
a.iloc[3]

np.int64(40)

In [ ]:
a.iloc[[1,2,3]]

1    20
2    30
3    40
Name: calaries, dtype: int64

In [ ]:
 index=["apple","orange","copico","cared","dongy","waste"]

In [ ]:
a.index=index
a

apple     10
orange    20
copico    30
cared     40
dongy     50
waste     60
Name: calaries, dtype: int64

In [ ]:
a["waste"]

np.int64(60)

In [ ]:
a.iloc[3]

np.int64(40)

In [ ]:
#loc label based indexing
a.loc["apple"]

np.int64(10)

In [ ]:
data ={
    "name":["arun","kumar","velu","kali","muththu"],
    "age":[20,23,43,23,23],
    "department":["HR","IT","HR","IT","IT"],
    "salary":[1000,28000,12000,21000,37000]
       }

In [ ]:
data

{'name': ['arun', 'kumar', 'velu', 'kali', 'muththu'],
 'age': [20, 23, 43, 23, 23],
 'department': ['HR', 'IT', 'HR', 'IT', 'IT'],
 'salary': [1000, 28000, 12000, 21000, 37000]}

In [ ]:
df=pd.DataFrame(data)
df

      name  age department  salary
0     arun   20         HR    1000
1    kumar   23         IT   28000
2     velu   43         HR   12000
3     kali   23         IT   21000
4  muththu   23         IT   37000

In [ ]:
df.head(2)

    name  age department  salary
0   arun   20         HR    1000
1  kumar   23         IT   28000

In [ ]:
df.tail(3)

      name  age department  salary
2     velu   43         HR   12000
3     kali   23         IT   21000
4  muththu   23         IT   37000

In [ ]:
df.iloc[0:1,:3]

   name  age department
0  arun   20         HR

In [ ]:
df.loc[0:1,["name","salary"]]

    name  salary
0   arun    1000
1  kumar   28000

In [ ]:
df["age"]

0    20
1    23
2    43
3    23
4    23
Name: age, dtype: int64

In [ ]:
df.drop("age" ,axis=1)

      name department  salary
0     arun         HR    1000
1    kumar         IT   28000
2     velu         HR   12000
3     kali         IT   21000
4  muththu         IT   37000

In [ ]:
data

{'name': ['arun', 'kumar', 'velu', 'kali', 'muththu'],
 'age': [20, 23, 43, 23, 23],
 'department': ['HR', 'IT', 'HR', 'IT', 'IT'],
 'salary': [1000, 28000, 12000, 21000, 37000]}

In [ ]:
df

      name  age department  salary
0     arun   20         HR    1000
1    kumar   23         IT   28000
2     velu   43         HR   12000
3     kali   23         IT   21000
4  muththu   23         IT   37000

In [ ]:
df.drop("salary" ,axis=1,)

      name  age department
0     arun   20         HR
1    kumar   23         IT
2     velu   43         HR
3     kali   23         IT
4  muththu   23         IT

In [ ]:
df

      name  age department  salary
0     arun   20         HR    1000
1    kumar   23         IT   28000
2     velu   43         HR   12000
3     kali   23         IT   21000
4  muththu   23         IT   37000

In [ ]:
df

      name  age department  salary
0     arun   20         HR    1000
1    kumar   23         IT   28000
2     velu   43         HR   12000
3     kali   23         IT   21000
4  muththu   23         IT   37000

In [ ]:
df.shape

(5, 4)

In [ ]:
df.info

<bound method DataFrame.info of       name  age department  salary
0     arun   20         HR    1000
1    kumar   23         IT   28000
2     velu   43         HR   12000
3     kali   23         IT   21000
4  muththu   23         IT   37000>

In [ ]:
df.describe()

             age        salary
count   5.000000      5.000000
mean   26.400000  19800.000000
std     9.370165  13953.494186
min    20.000000   1000.000000
25%    23.000000  12000.000000
50%    23.000000  21000.000000
75%    23.000000  28000.000000
max    43.000000  37000.000000

In [ ]:
df["salary"]=df["salary"]+5000

In [ ]:
df

      name  age department  salary
0     arun   20         HR    6000
1    kumar   23         IT   33000
2     velu   43         HR   17000
3     kali   23         IT   26000
4  muththu   23         IT   42000

In [ ]:
df["salary"]

0     6000
1    33000
2    17000
3    26000
4    42000
Name: salary, dtype: int64

In [ ]:
df

      name  age department  salary
0     arun   20         HR    6000
1    kumar   23         IT   33000
2     velu   43         HR   17000
3     kali   23         IT   26000
4  muththu   23         IT   42000

In [ ]:
 df.rename(columns={"department":"dept"},inplace=True)

In [ ]:
df

      name  age dept  salary
0     arun   20   HR    6000
1    kumar   23   IT   33000
2     velu   43   HR   17000
3     kali   23   IT   26000
4  muththu   23   IT   42000

In [ ]:
df["dept"].unique()

array(['HR', 'IT'], dtype=object)

In [ ]:
df["dept"].value_counts()

dept
IT    3
HR    2
Name: count, dtype: int64

In [ ]:
df["promoted salary"]=df["salary"]+200

In [ ]:
df

      name  age dept  salary  promoted salary
0     arun   20   HR    6000             6200
1    kumar   23   IT   33000            33200
2     velu   43   HR   17000            17200
3     kali   23   IT   26000            26200
4  muththu   23   IT   42000            42200

In [ ]:
df.isnull().sum()

name               0
age                0
dept               0
salary             0
promoted salary    0
dtype: int64

In [ ]:
df.dropna()

      name  age dept  salary  promoted salary
0     arun   20   HR    6000             6200
1    kumar   23   IT   33000            33200
2     velu   43   HR   17000            17200
3     kali   23   IT   26000            26200
4  muththu   23   IT   42000            42200

In [ ]:
df.dropna( how="any")

      name  age dept  salary  promoted salary
0     arun   20   HR    6000             6200
1    kumar   23   IT   33000            33200
2     velu   43   HR   17000            17200
3     kali   23   IT   26000            26200
4  muththu   23   IT   42000            42200

In [ ]:
df.dropna(how="all")

      name  age dept  salary  promoted salary
0     arun   20   HR    6000             6200
1    kumar   23   IT   33000            33200
2     velu   43   HR   17000            17200
3     kali   23   IT   26000            26200
4  muththu   23   IT   42000            42200

In [ ]:
df.fillna(0)

      name  age dept  salary  promoted salary
0     arun   20   HR    6000             6200
1    kumar   23   IT   33000            33200
2     velu   43   HR   17000            17200
3     kali   23   IT   26000            26200
4  muththu   23   IT   42000            42200

In [ ]:
df["age"].fillna(df["age"].mean())

0    20
1    23
2    43
3    23
4    23
Name: age, dtype: int64

In [ ]:
df["salary"].fillna(df["salary"].median())

0     6000
1    33000
2    17000
3    26000
4    42000
Name: salary, dtype: int64

In [ ]:
df["salary"].fillna(method="ffill")

/tmp/ipykernel_162/4275000142.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["salary"].fillna(method="ffill")

0     6000
1    33000
2    17000
3    26000
4    42000
Name: salary, dtype: int64

In [ ]:
df["salary"].fillna(method="bfill")

/tmp/ipykernel_162/3559053075.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["salary"].fillna(method="bfill")

0     6000
1    33000
2    17000
3    26000
4    42000
Name: salary, dtype: int64

In [ ]:
#replace
df["name"].replace("arun","kalai")

0      kalai
1      kumar
2       velu
3       kali
4    muththu
Name: name, dtype: object

In [ ]:
df

      name  age dept  salary  promoted salary
0     arun   20   HR    6000             6200
1    kumar   23   IT   33000            33200
2     velu   43   HR   17000            17200
3     kali   23   IT   26000            26200
4  muththu   23   IT   42000            42200

In [ ]:
df["name"]=df["name"].replace("arun","kalai")

In [ ]:
df

      name  age dept  salary  promoted salary
0    kalai   20   HR    6000             6200
1    kumar   23   IT   33000            33200
2     velu   43   HR   17000            17200
3     kali   23   IT   26000            26200
4  muththu   23   IT   42000            42200

In [ ]:
df_dup=df[df.duplicated(keep="first")]
df_dup

Empty DataFrame
Columns: [name, age, dept, salary, promoted salary]
Index: []